name: amiconnected
summary: A
description: |
  A.
version: '1.0.0'
grade: stable
confinement: strict
base: core18
license: GPL-3.0
icon: snap/gui/amiconnected.png

parts:

  webview:
    plugin: python
    build-packages:
      - libwebkit2gtk-4.0-dev
      - libgtk-3-dev
      - python3.6-dev
      - locales-all
    python-packages:
      - webview == 0.1.5

  amiconnected:
    plugin: dump
    source: ./amiconnected-python
    organize:
      amiconnected-python: amiconnected-python
    after: [webview]

apps:
  amiconnected:
    command: usr/bin/python3 $SNAP/main.py
    desktop: amiconnected.desktop
    extensions:
      - gnome-3-28    
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin:$PATH
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.6/site-packages:$SNAP/usr/local/lib/python3.6/dist-packages:$SNAP/usr/lib/python3.6/dist-packages:$PYTHONPATH
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
    plugs:
      - x11
      - unity7
      - home
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - gsettings
      - opengl
      - removable-media

plugs:
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk2-common-themes
  gtk-2-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
